from .user import UserViewSet
from .item_acervo import ItemAcervoViewSet
from .colecao import ColecaoViewSet
from .coletor import ColetorViewSet
from .materia_prima import MateriaPrimaViewSet
from .subtipo_materia_prima import SubtipoMateriaPrimaViewSet
from .imagem_item import ImagemItemViewSet
from .movimentacao_item import MovimentacaoItemViewSet
from .auditoria import AuditoriaViewSet
from .localizacao import LocalizacaoViewSet